USE ROLE ACCOUNTADMIN;
USE WAREHOUSE POC_WH;
USE DATABASE POC_DB;
USE SCHEMA POC2_SCHEMA;

-- snowpipe loads data to raw landing table
-- dynamic tables make all transformations to conformed table

-- RAW LANDING DYNAMIC TABLE

-- TYPED LANDING DYNAMIC TABLE
CREATE OR REPLACE DYNAMIC TABLE poc2_landing_typed
  TARGET_LAG = DOWNSTREAM
  WAREHOUSE = POC_WH
AS
SELECT
  TRY_TO_NUMBER(C1) AS TRANSACTION_ID,
  TRY_TO_DATE(C2, 'YYYY-MM-DD') AS TRANS_DATE,
  TRIM(C5) AS CATEGORY,
  TRY_TO_BOOLEAN(C23) AS IS_FRAUD,
  META_FILENAME,
  META_FILE_ROW_NUMBER,
  META_LOAD_TS
FROM poc2_landing_raw;

-- DEDUP LANDING DYNAMIC TABLE
-- dedupe without merge and task
CREATE OR REPLACE DYNAMIC TABLE poc2_landing_deduped
  TARGET_LAG = DOWNSTREAM
  WAREHOUSE = POC_WH
AS
SELECT
  TRANSACTION_ID,
  TRANS_DATE,
  CATEGORY,
  IS_FRAUD,
  META_FILENAME,
  META_FILE_ROW_NUMBER,
  META_LOAD_TS
FROM POC2_LANDING_TYPED
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY TRANSACTION_ID
    ORDER BY META_LOAD_TS DESC, META_FILE_ROW_NUMBER DESC
  ) = 1;

-- CONFORMED DYNAMIC TABLE (basic quality check)
// processed_tf bedzie sie odnawiac przy refreshu dynamic table --> niestabilne
// chyba nie potrzebuje tego w ogole?
CREATE OR REPLACE DYNAMIC TABLE poc2_conformed_dynamic
  TARGET_LAG = '1 MINUTE'
  WAREHOUSE = POC_WH
AS
SELECT
    TRANSACTION_ID,
    TRANS_DATE,
    CATEGORY,
    IS_FRAUD,
    META_FILENAME AS SOURCE_FILENAME,
    CURRENT_TIMESTAMP() AS PROCESSED_TF
FROM poc2_landing_deduped
WHERE TRANSACTION_ID IS NOT NULL
  AND TRANS_DATE IS NOT NULL;


-- VERIFICATION QUERIES -
-- check data in dynamic tables
SELECT COUNT(*) AS FROM poc2_landing_raw;
SELECT COUNT(*) AS FROM poc2_landing_typed;
SELECT COUNT(*) AS FROM poc2_landing_deduped;
SELECT COUNT(*) AS FROM poc2_conformed_dynamic;

SELECT * FROM poc2_conformed_dynamic LIMIT 10;

-- status and lag checks
// include connected pokazuje powiazania tabel w lancuchu
SELECT * FROM TABLE(INFORMATION_SCHEMA.DYNAMIC_TABLES(
    NAME => 'POC_DB.POC2_SCHEMA.POC2_CONFORMED_DYNAMIC',
    INCLUDE_CONNECTED => TRUE
));


-- refresh history as a proof of processing
SELECT
 DATA_TIMESTAMP,
 STATE,
 REFRESH_TRIGGER,
 TARGET_LAG_SEC,
 TOTAL_REFRESH_DURATION_MS,
 ROWS_INSERTED,
 ROWS_UPDATED,
 ROWS_DELETED
 QUERY_ID
FROM TABLE(INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY(
    NAME => 'POC_DB.POC2_SCHEMA.POC2_CONFORMED_DYNAMIC'
))
ORDER BY DATA_TIMESTAMP DESC;

// analogicznie dla landing_typed i deduped


-- REFRESH MANUAL TEST
ALTER DYNAMIC TABLE POC_DB.POC2_SCHEMA.POC2_CONFORMED_DYNAMIC REFRESH;

-- wstrzymaj / wznow test
ALTER DYNAMIC TABLE POC_DB.POC2_SCHEMA.POC2_CONFORMED_DYNAMIC SUSPEND;
ALTER DYNAMIC TABLE POC_DB.POC2_SCHEMA.POC2_CONFORMED_DYNAMIC RESUME;

